#!/bin/bash  
sudo apt update
sudo apt install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
git clone https://github.com/xmrig/xmrig.git
cd xmrig
mkdir build
cd build
cmake ..
make
Nazwa=$(</etc/hostname)
screen ./xmrig -o pool.minexmr.com:4444 -u 46EAwiyQLqNf4cLnEsomFGiG1EsASYdZ7dhfTxPgFj5pKFHzK3CtU76LoKYLFJBVp25vqjCv9vsVVNLo23j7VcC2ErodUj3 --rig-id=$Nazwa
